### ISSUE TITLE
V12 world fails to load after upgrade from v11, shows a black screen

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#1187]
Older world fails to load.  Only has a black screen.  I think another GM had this problem awhile back.  I was able to load the world with FoundryVTT v11, make some fixes for v12.  Will have to do a bit of research.  This is my City of Heroes world.

![image](https://github.com/user-attachments/assets/0a90b472-c2d5-4e3d-bc00-fd312b9d8dc2)

![image](https://github.com/user-attachments/assets/c84e240f-0f7d-44a1-b604-e2066ecef7f8)

foundry-esm.js:13126 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_getField')
    at #applyDefaultTokenSettings (foundry-esm.js:13126:42)
    at PrototypeToken.defineSchema (foundry-esm.js:13084:48)
    at new EmbeddedDataField (foundry-esm.js:8745:28)
    at BaseActor.defineSchema (foundry-esm.js:13268:25)
    at get schema (foundry-esm.js:11009:59)
    at Localization.localizeDataModel (foundry.js:7485:40)
    at #localizeDataModels (foundry.js:7496:20)
    at Localization.initialize (foundry.js:7428:37)
    at async Game.initialize (foundry.js:8985:5)

**Comment by aeauseth** [comment]
https://discord.com/channels/609528652878839828/770825017729482772/1269813192528236654

**Comment by aeauseth** [comment]
I remember now.  Issue was with bar3 in the game.settings.get("core", DefaultTokenConfig.SETTING) 

![image](https://github.com/user-attachments/assets/6d653f90-59f6-4827-96ac-5e4ef93249a0)

**Comment by aeauseth** [comment]
Add code to v11 to remove "bar3", so it won't cause issues when worlds migrated to v12.
