### ISSUE TITLE
TRANSFORM prevents actor load

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#1574]
![image](https://github.com/user-attachments/assets/57dd21a3-64e9-4635-a67a-d0ff4c714086)

![image](https://github.com/user-attachments/assets/d7e79d79-41f1-4214-9e9f-59fc1b98ef85)

```
config.mjs:5919 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'OPTIONID')
    at Object.costPerLevel (config.mjs:5919:37)
    at HeroSystem6eItem.calcBasePointsPlusAdders (item.mjs:2567:59)
    at HeroSystem6eItem.calcItemPoints (item.mjs:2410:24)
    at HeroSystem6eItem.determinePointCosts (item.mjs:943:24)
    at HeroSystem6eItem._postUpload (item.mjs:1582:24)
    at actor.mjs:1737:31
    at Array.map (<anonymous>)
    at HeroSystem6eActor.uploadFromXml (actor.mjs:1737:18)
    at async HeroSystemActorSheet.<anonymous> (actor-sheet.mjs:1330:13)
```

**Comment by aeauseth** [comment]
Looks like we pass in a adder not an item.  Fix was to check for both.  Unclear if we really need the item.

```js
            costPerLevel: function (item) {
                // item appears to be an adder in some cases
                switch (item.system?.OPTIONID || item.OPTIONID) {
                    case "COSMETIC":
                        return item.is5e ? 5 : 3;
                    case "MINOR":
                        return item.is5e ? 10 : 5;
                    case "MAJOR":
                        return item.is5e ? 15 : 10;
                    case "SEVERE":
                        return 15;
                }
                // This should never happen
                console.error(`Invalid TRANSFORM option ID: ${item.system.OPTIONID}`);
                return 1;
            },
```
