### ISSUE TITLE
Combat tracker crash (player only?)

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#650]
foundry.js:753 TypeError: An error occurred while rendering HeroSystem6eCombatTracker 11. Cannot read properties of undefined (reading 'css')
    at HeroSystem6eCombatTracker.getData (combatTracker.js:58:54)
    at async HeroSystem6eCombatTracker._render (foundry.js:5812:18)
    at async HeroSystem6eCombatTracker._render (foundry.js:69030:5)

**Comment by aeauseth** [comment]
Occurs where there are non-visible tokens in the combat tracker.

**Comment by aeauseth** [comment]
Fixed in 3.0.55
